# Generated by Django 5.2.1 on 2025-05-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrequest',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
