# Generated by Django 5.2.1 on 2025-05-22 16:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrequest',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phonecharge',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_charges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phonecharge',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='payments.phonenumber'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='creditrequest',
            index=models.Index(fields=['status'], name='payments_cr_status_309689_idx'),
        ),
        migrations.AddConstraint(
            model_name='creditrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.01'))), name='creditrequest_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='phonecharge',
            index=models.Index(fields=['seller'], name='payments_ph_seller__d0825a_idx'),
        ),
        migrations.AddIndex(
            model_name='phonecharge',
            index=models.Index(fields=['phone_number'], name='payments_ph_phone_n_8c0cb1_idx'),
        ),
        migrations.AddConstraint(
            model_name='phonecharge',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.01'))), name='phonecharge_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.01'))), name='transaction_amount_positive'),
        ),
    ]
