# Generated by Django 5.2.1 on 2025-05-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='phonecharge',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='creditrequest',
            name='creditrequest_amount_positive',
        ),
        migrations.RemoveConstraint(
            model_name='phonecharge',
            name='phonecharge_amount_positive',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='transaction_amount_positive',
        ),
        migrations.RemoveIndex(
            model_name='creditrequest',
            name='payments_cr_status_309689_idx',
        ),
        migrations.RemoveIndex(
            model_name='phonecharge',
            name='payments_ph_seller__d0825a_idx',
        ),
        migrations.RemoveIndex(
            model_name='phonecharge',
            name='payments_ph_phone_n_8c0cb1_idx',
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
