# Generated by Django 5.2.1 on 2025-05-19 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_creditrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='credit_requests', to='payments.status'),
        ),
    ]
