# Generated by Django 5.2.1 on 2025-05-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_creditrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
