# Generated by Django 5.2.1 on 2025-05-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_creditrequest_amount_alter_phonenumber_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecharge',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
